version: "3.9"
services:
  service3:
    container_name: "service3"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - my-network

networks:
  my-network:
    external: true