version: "3.9"
services:
  service2:
    container_name: "service2"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - my-network

networks:
  my-network:
    external: true