version: "3.9"
services:
  service1:
    container_name: "service1"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - my-network

networks:
  my-network:
    external: true